name: Deploy to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --without google --no-root || (sleep 10 && poetry install --without google --no-root) 
    
    - name: Run tests
      run: |
        cp .env.test .env
        CI=true poetry run pytest
    
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/ai-event-planner:${{ github.sha }} .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/ai-event-planner:${{ github.sha }}
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ai-event-planner'
        images: '${{ secrets.ACR_LOGIN_SERVER }}/ai-event-planner:${{ github.sha }}'
    
    - name: Run database migrations
      run: |
        az webapp ssh --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ai-event-planner --command "python scripts/migrate.py"
